# Generated by Django 5.0.7 on 2024-07-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=80)),
                ('province', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
